_wandb:
    value:
        cli_version: 0.28.1
        e:
            81kmebge7nlxtanhu5fvltn3izwutof0:
                args:
                    - results/qgnn/qg_jets_metrics_lorentz800_seed*.json
                    - --output
                    - results/qgnn/qg_jets_metrics_lorentz800_summary.json
                    - --wandb-mode
                    - online
                    - --wandb-group
                    - qgnn-jet-classification-lorentz800
                    - --wandb-name
                    - qgnn-M8-lorentz800-summary
                codePath: experiments/aggregate_qgnn_repeats.py
                codePathLocal: experiments/aggregate_qgnn_repeats.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1599929212928"
                        used: "1034156802048"
                email: stmmc@umsystem.edu
                executable: /opt/conda/envs/graph-vls/bin/python
                git:
                    commit: 0e830cab043400e39fb274d32ce926d5c49835c4
                    remote: git@github.com:SMATousi/graph-vls.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-6d639b10-70fe-303c-3580-1e02f54673d7
                host: 2-ali-100-dep-vigir-575d848757-fv66n
                memory:
                    total: "1081702211584"
                os: Linux-6.8.0-136-generic-x86_64-with-glibc2.35
                program: /root/home/graph-vls/experiments/aggregate_qgnn_repeats.py
                python: CPython 3.11.15
                root: /root/home/graph-vls
                startedAt: "2026-08-03T05:15:13.294166Z"
                writerId: 81kmebge7nlxtanhu5fvltn3izwutof0
        m: []
        python_version: 3.11.15
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
num_runs:
    value: 5
source_files:
    value:
        - results/qgnn/qg_jets_metrics_lorentz800_seed42.json
        - results/qgnn/qg_jets_metrics_lorentz800_seed43.json
        - results/qgnn/qg_jets_metrics_lorentz800_seed44.json
        - results/qgnn/qg_jets_metrics_lorentz800_seed45.json
        - results/qgnn/qg_jets_metrics_lorentz800_seed46.json
