defaults:
  - data: qg_jets
  - _self_

gvls_checkpoint_path: checkpoints/gvls_jets_m4.pt
qgnn_checkpoint_path: checkpoints/qgnn_jets_m4.pt
results_path: results/qgnn/qg_jets_metrics.json

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false
